#!/bin/bash
# GPU Monitoring Commands for mesh-hpc

echo "=========================================="
echo "GPU MONITORING COMMANDS"
echo "=========================================="
echo ""
echo "1. REAL-TIME GPU STATUS (updates every 2 seconds):"
echo "   watch -n 2 nvidia-smi"
echo ""
echo "2. SINGLE GPU CHECK:"
echo "   nvidia-smi"
echo ""
echo "3. COMPACT GPU INFO:"
echo "   nvidia-smi --query-gpu=index,name,temperature.gpu,utilization.gpu,utilization.memory,memory.used,memory.total --format=csv"
echo ""
echo "4. CHECK YOUR JOBS:"
echo "   squeue -u \$USER"
echo ""
echo "5. MONITOR JOB OUTPUT:"
echo "   tail -f ./logs/Phase1_DataPrep_*.out"
echo ""
echo "6. CHECK BOTH GPUs SEPARATELY:"
echo "   nvidia-smi -i 0  # GPU 0"
echo "   nvidia-smi -i 1  # GPU 1"
echo ""
echo "=========================================="
echo "RUNNING GPU STATUS NOW:"
echo "=========================================="
nvidia-smi
echo ""
echo "=========================================="
echo "CURRENT SLURM QUEUE:"
echo "=========================================="
squeue
