#!/bin/bash
#SBATCH --job-name=unet_train
#SBATCH --output=logs/train_%j.out
#SBATCH --error=logs/train_%j.err
#SBATCH --time=72:00:00
#SBATCH --partition=mesh
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=90G
#SBATCH --oversubscribe

# ============================================================================
# Phase 3: 3D U-Net Training with MONAI
# ============================================================================
# This script trains the final 3D segmentation model using MONAI framework.
# Uses the high-quality pseudo-masks generated by MedSAM in Phase 2.
# REQUIRES GPU - Single GPU for now (multi-GPU not working yet).
#
# Usage: sbatch slurm_train_unet.sh
# ============================================================================

echo "=========================================="
echo "3D U-Net Training - Phase 3"
echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURMD_NODENAME"
echo "Started at: $(date)"
echo ""

# Create logs directory if it doesn't exist
mkdir -p logs

# Load conda environment
source ~/.bashrc
conda activate abdomen_scanner

# Function to intelligently select GPU with the lowest combined memory and GPU utilization
select_optimal_gpu() {
    gpu_info=$(nvidia-smi --query-gpu=index,memory.used,memory.total,utilization.gpu --format=csv,noheader,nounits)
    
    best_gpu=-1
    best_score=999999
    
    while IFS=',' read -r gpu_id mem_used mem_total gpu_util; do
        # Trim whitespace
        gpu_id=$(echo "$gpu_id" | xargs)
        mem_used=$(echo "$mem_used" | xargs)
        mem_total=$(echo "$mem_total" | xargs)
        gpu_util=$(echo "$gpu_util" | xargs)
        
        # Avoid division by zero if mem_total is 0 for some reason
        if [ "$mem_total" -eq 0 ]; then
            continue
        fi

        mem_percent=$((mem_used * 100 / mem_total))
        score=$((mem_percent + gpu_util))
        
        if [ "$score" -lt "$best_score" ]; then
            best_score=$score
            best_gpu=$gpu_id
        fi
    done <<< "$gpu_info"
    
    echo $best_gpu
}

# Select GPU intelligently
if [ -n "$REQUESTED_GPU" ]; then
    export CUDA_VISIBLE_DEVICES=$REQUESTED_GPU
else
    selected_gpu=$(select_optimal_gpu)
    if [ "$selected_gpu" -eq -1 ]; then
        echo "Error: Could not find an available GPU." >&2
        exit 1
    fi
    export CUDA_VISIBLE_DEVICES=$selected_gpu
fi

# Check GPU
echo "GPU Information:"
nvidia-smi
echo ""

# Verify PyTorch GPU access
echo "PyTorch Configuration:"
python -c "import torch; print(f'PyTorch version: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA version: {torch.version.cuda}'); print(f'Device count: {torch.cuda.device_count()}'); print(f'Current device: {torch.cuda.current_device()}'); print(f'Device name: {torch.cuda.get_device_name(0)}')"
echo ""

# Check MONAI installation
echo "MONAI Configuration:"
python -c "import monai; print(f'MONAI version: {monai.__version__}')"
echo ""

# Training parameters
CONFIG_FILE="configs/config.yaml"
EPOCHS=300
BATCH_SIZE=2
NUM_WORKERS=8
LEARNING_RATE=0.0002

echo "Training Configuration:"
echo "  Config file: $CONFIG_FILE"
echo "  Epochs: $EPOCHS"
echo "  Batch size: $BATCH_SIZE"
echo "  Workers: $NUM_WORKERS"
echo "  Learning rate: $LEARNING_RATE"
echo ""

# Create checkpoint directory
mkdir -p models/checkpoints

# Start training
echo "=========================================="
echo "Starting 3D U-Net Training..."
echo "=========================================="
echo ""

python scripts/train_monai.py \
    --config $CONFIG_FILE \
    --epochs $EPOCHS \
    --batch-size $BATCH_SIZE \
    --num-workers $NUM_WORKERS \
    --lr $LEARNING_RATE \
    --output-dir models \
    --checkpoint-dir models/checkpoints \
    --log-dir logs/tensorboard

# Check training exit status
TRAIN_EXIT_CODE=$?

echo ""
echo "=========================================="
if [ $TRAIN_EXIT_CODE -eq 0 ]; then
    echo "✓ Training completed successfully!"
    echo ""
    echo "Outputs:"
    echo "  - Best model: models/best_model.pth"
    echo "  - Final model: models/final_model.pth"
    echo "  - Checkpoints: models/checkpoints/"
    echo "  - TensorBoard logs: logs/tensorboard/"
    echo ""
    echo "To download the model:"
    echo "  scp user@mesh-hpc:~/abdomen-scanner/models/best_model.pth /local/path/"
else
    echo "✗ Training failed with exit code: $TRAIN_EXIT_CODE"
    echo "Check the error log for details."
    exit 1
fi

echo ""
echo "Finished at: $(date)"
echo "Total runtime: $SECONDS seconds"
echo "=========================================="
